### PR TITLE
WIP: Update hyper related deps and bump version

### PR DESCRIPTION
**Pull request by Eijebong**

### CODE REVIEW

**Comment by nox** [comment]
@Eijebong Why is this WIP?

**Comment by Eijebong** [comment]
Because I'm still waiting for warp to get released to be able to update it in webdriver. Otherwise we'll dupe hyper in servo if we need anything else from this crate

**Comment by nox** [comment]
Ack.

**Comment by atouchet** [comment]
The new release of warp is out now.

**Comment by Eijebong** [comment]
Yeah, and webdriver has been updated upstream but not released yet

**Comment by atouchet** [comment]
webdriver 0.41 is out now.

**Comment by ghostd** [comment]
Hi,

Is this still WIP or can we release a new version to bump hyper into servo? (BTW last hyper version is now 0.14)

Regards

**Comment by jdm** [comment]
Nobody is actively working on the upgrade. One issue with upgrading hyper to 0.14 is that it transitively depends on mio 0.7, and https://github.com/servo/servo/issues/26896 was a concern. Now that we're not actively shipping a UWP product that may be less important than it used to be.

**Pull request closed without merging**
