### PR TITLE
Add homu configuration.

### PR DESCRIPTION
**Pull request by jdm**

### CODE REVIEW

**Comment by jdm** [comment]
The webhook isn't working yet.

**Comment by jdm** [comment]
There's something weird about this repository; possibly because it was transferred.
```
Traceback (most recent call last):
  File "/home/servo/homu/_venv/bin/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/home/servo/homu/_venv/bin/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/home/servo/homu/_venv/lib/python3.4/site-packages/homu/server.py", line 207, in callback
    repo = get_repo(repo_label, repo_cfg)
  File "/home/servo/homu/_venv/lib/python3.4/site-packages/homu/server.py", line 58, in get_repo
    assert repo.owner.login == repo_cfg['owner']
AttributeError: 'NoneType' object has no attribute 'owner'
Traceback (most recent call last):
  File "/home/servo/homu/_venv/bin/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/home/servo/homu/_venv/bin/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/home/servo/homu/_venv/lib/python3.4/site-packages/homu/server.py", line 116, in queue
    if repo_label in g.repos and g.repos[repo_label].treeclosed >= 0:
AttributeError: 'NoneType' object has no attribute 'treeclosed'
```

**Comment by nox** [comment]
This uses bors-ng, do we really need it to use homu?

**Comment by jdm** [comment]
It's nice to have a uniform way of merging PRs across our active repositories.

**Comment by nox** [comment]
Please remove bors.toml while at it.

**Comment by nox** [comment]
I'm confused, the webhook isn't present in some Travis configurations, e.g. `rust-url`.

**Pull request merged**
