### PR TITLE
Add hyper::Uri support 

### PR DESCRIPTION
**Pull request by DarrenTsung**
Based on PR #20 && #21, modified with feedback.

I also will make another PR for updating to hyper 0.12, but I think we can land this separately so there's a commit / release that supports hyper 0.11.

### CODE REVIEW

**Comment by DarrenTsung** [comment]
@nox any thoughts on this PR?

**Comment by nox** [comment]
Could you remove everything that doesn't pertain to supporting `hyper::Uri` from it? Is the bump even needed to support it?

**Comment by DarrenTsung** [comment]
`hyper::Uri` was introduced as a replacement to `hyper::Url` in `hyper 0.11` which is why the version bumps for `hyper` are necessary. I believe this is all part of a movement to refactor out some common http types into the `hyperium/http` crate. 

Additionally `hyper 0.11` changed up a couple things like the `mime` dependency and `Headers` API change which is why there is code changes around that.

So I think all the changes are necessary to supporting `hyper::Uri` + `hyper 0.11`, but please let me know if you see something that I missed!

**Comment by DarrenTsung** [comment]
@nox any update on this?

**Pull request closed without merging**
