### PR TITLE
Bump mime to 0.3 and hyper to 0.12

### PR DESCRIPTION
**Pull request by Eijebong**
ping @avadacatavra

### CODE REVIEW

**Comment by avadacatavra** [comment]
@Eijebong looks good to me

**Comment by Eijebong** [comment]
So I have no idea why, but @KiChjang asked me to rebase this, it's done now ;)

**Comment by nox** [comment]
Remove "[WIP]" from the commit title and I will land this.

**Comment by Eijebong** [comment]
@nox Do we want to land this now ?

**Comment by nox** [comment]
Actually not sure.

**Comment by Eijebong** [comment]
Yeah, I thinks it's better to wait for everything to be ready (not that this crate is super active but you never know).

**Comment by Eijebong** [comment]
Ok this is ready now !

**Comment by nox** [comment]
https://github.com/hyperium/headers/issues/20

**Pull request merged**
